language: python

sudo: false

cache: pip

matrix:
  include:
    - python: 3.4
      env:
        - TOXENV=py34
        - WITH_GCOV=1
    - python: 3.5
      env:
        - TOXENV=py35
        - WITH_GCOV=1
    - python: 3.6
      env:
        - TOXENV=py36
        - WITH_GCOV=1

install:
  - pip install "pip>=7.1.0"
  - pip install tox-travis pytest pytest-cov

script: tox

after_success:
  - python -m coverage combine
  - python -m coverage report --show-missing