language: python

sudo: false

#cache: pip

matrix:
  include:
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      env:
        - TOXENV=py37
    - python: 3.8
      env:
        - TOXENV=py38

install:
  - pip install "pip>=7.1.0" six
  - python setup.py install_egg_info
  - pip install tox-travis coverage coveralls pytest tox

script:
  - tox
  - coverage run --source ldap_filter -m py.test
  - coverage report -m

after_success:
  - coveralls