language: python

sudo: false

cache: pip

matrix:
  include:
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36

install:
  - pip install "pip>=7.1.0"
  - pip install tox-travis

script:
  - tox
  - coverage run --source ldap_filter -m py.test
  - coverage report -m

after_success:
  - coveralls